Use netlify hosting

diff --git a/.github/workflows/create-and-deploy-portals.yml b/.github/workflows/create-and-deploy-portals.yml
--- a/.github/workflows/create-and-deploy-portals.yml
+++ b/.github/workflows/create-and-deploy-portals.yml
@@ -1,75 +1,95 @@
-name: Generate API Portal
+name: Deploy Static Portal
 
-# Controls when the workflow will run
 on:
+  workflow_dispatch:  
   push:
-    branches:
-      - main
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
- 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+    branches: 
+      - master 
+      
 jobs:
-  Generate-Portal:
+  generate-portal:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
-
-      - name: print branch
-        run: echo '${{ github.ref }}'
+       
+    - uses: actions/checkout@v1
+      name : checkout-repo
+      id: checkout-repo  
       
-      # Zip the contents of the repository
-      - name: Zip build files for staging deployment
-        run: |
-          zip -qq -r portal-input.zip . -x '/.git/*' '/.github/*'
-
-      # Call Apimatic Endpoint to generate Portal
-      - name: Generate Portal
-        id: generate-portal
-        run: | 
-          RESPONSE=`curl -s --write-out '%{http_code}\t%{content_type}' --request POST --url 'https://api.apimatic.io/portal' \
-            -H 'Authorization:X-Auth-Key ${{ secrets.APIMATIC_API_KEY }}' -F 'file=@portal-input.zip' -OJ`;
-          
-          HTTP_CODE=$(echo $RESPONSE | cut -d " " -f 1);
-          CONTENT_TYPE=$(echo $RESPONSE | cut -d " " -f 2);
-          echo "HTTP_CODE=$HTTP_CODE" >> $GITHUB_OUTPUT;
-          echo "CONTENT_TYPE=$CONTENT_TYPE" >> $GITHUB_OUTPUT;
-   
-      # Unzip the generated Portal output
-      - name: Unzip Portal
-        if: ${{steps.generate-portal.outputs.HTTP_CODE == '200'}}
-        run: unzip -qq portal.zip -d portal
-    
-      # Upload Portal Artifact
-      - name: Upload Artifact
-        if: ${{steps.generate-portal.outputs.HTTP_CODE == '200' }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: portal
-          path: portal
-
-      # Unzip error file if error code is 422 with a zip file
-      - name: Unzip error file
-        if: ${{steps.generate-portal.outputs.HTTP_CODE == '422' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
-        run: unzip -qq error.zip -d error
-
-      # Upload error.zip if error code is 422 with a zip file
-      - name: Upload error.zip
-        if: ${{steps.generate-portal.outputs.HTTP_CODE == '422' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
-        uses: actions/upload-artifact@v3.1.1
-        with:
-          name: error
-          path: error.zip
+    - name: Zip files
+      run: zip -qq -r portal-input.zip . -x '/.git/*' '/.github/*'
+      
+    # Call Apimatic Endpoint to generate Portal
+    - name: Call build endpoint
+      id: generate-portal
+      run: | 
+        RESPONSE=`curl -s --write-out '%{http_code}\t%{content_type}' --request POST --url 'https://api.apimatic.io/portal' \
+          -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@portal-input.zip' -OJ`;
         
-      # Publish updates to cloudflare
-      - name: Publish to Cloudflare Pages to main
-        if: steps.generate-portal.outputs.HTTP_CODE == '200'
-        uses: cloudflare/wrangler-action@2.0.0
-        with:
-          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-          command: pages deploy portal --branch=main --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
+        HTTP_CODE=$(echo $RESPONSE | cut -d " " -f 1);
+        CONTENT_TYPE=$(echo $RESPONSE | cut -d " " -f 2);
+        echo "HTTP_CODE=$HTTP_CODE" >> $GITHUB_OUTPUT;
+        echo "CONTENT_TYPE=$CONTENT_TYPE" >> $GITHUB_OUTPUT;
+
+    - name: list
+      run: ls
+
+    - name: Extract generated Portal
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '200'}}
+      run: unzip -qq portal.zip -d static-portal
+    
+    - name: list
+      run: ls
+      
+    - name: Deploy to Netlify
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '200'}}
+      uses: nwtgck/actions-netlify@v2.0
+      with:
+        publish-dir: './static-portal'
+        production-branch: master
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        deploy-message: "Deploy from GitHub Actions"
+        enable-pull-request-comment: false
+        enable-commit-comment: true
+        overwrites-pull-request-comment: true
+      env:
+        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
+        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
+      timeout-minutes: 2
+
+      # Upload Portal Artifact
+    - name: Upload Artifact
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '200' }}
+      uses: actions/upload-artifact@v3.1.1
+      with:
+        name: static-portal
+        path: static-portal
+
+    # Unzip error file if error code is 422 with a zip file
+    - name: Unzip error file
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '422' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
+      run: unzip -qq error.zip -d error
+      
+    # Upload error.zip if error code is 422 with a zip file
+    - name: Upload error.zip
+      if: ${{steps.generate-portal.outputs.HTTP_CODE == '422' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
+      uses: actions/upload-artifact@v3.1.1
+      with:
+        name: error
+        path: error
+
+    # Fail job if API response is not 200
+    - name: Log error if not successful
+      if: ${{steps.generate-portal.outputs.HTTP_CODE != '200' && steps.generate-portal.outputs.CONTENT_TYPE != 'application/zip'}}
+      run: |
+        echo "The Portal Generation request failed with response code ${{steps.generate-portal.outputs.HTTP_CODE}} and message $(cat portal)"; \
+        exit 1
+        
+    # Fail job if API response is not 200 and is a zip file
+    - name: Log error if not successful
+      if: ${{steps.generate-portal.outputs.HTTP_CODE != '200' && steps.generate-portal.outputs.CONTENT_TYPE == 'application/zip'}}
+      run: |
+        echo "The Portal Generation request failed with response code ${{steps.generate-portal.outputs.HTTP_CODE}}; \
+        exit 1
+    
+      
